name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby-version: ['2.7', '3.0', '3.1', '3.2', 'head']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      - name: Update RubyGems
        run: gem update --system

      - name: Install dependencies
        run: bundle install --jobs 4

      - name: Appraisals install
        run: bundle exec appraisal install

      - name: Tests
        run: bundle exec appraisal rspec

  rubocop:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby & Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Rubocop
        run: bundle exec rubocop
